<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="P_CP1_Calibration" Id="{3065913d-6b79-4f5a-bac4-18ef0f6d8554}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM P_CP1_Calibration
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//***********************************************************************************
//
// ETH Zürich / Robotic Fabrication Lab
// HIB C 13 / Stefano-Franscini-Platz 1
// CH-8093 Zürich
// 
// ***********************************************************************************
// 
// PROJECT     :  A061 
// 
// FUNCTION    :  Step chain for Concrete pump calibration
// 
// AUTHOR      :  Weiting Chen / Philippe Fleischmann
// 
// EMAIL       :  
// 
// Copyright   :  
//
// ***********************************************************************************
//
// placeholder for concrete pump calibration]]></ST>
    </Implementation>
    <LineIds Name="P_CP1_Calibration">
      <LineId Id="6" Count="17" />
      <LineId Id="5" Count="0" />
      <LineId Id="24" Count="1" />
    </LineIds>
  </POU>
</TcPlcObject>