<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="P_ModeSelector" Id="{0eb7d8c2-292e-4a26-bb54-34c9ce7294b6}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM P_ModeSelector
VAR
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//***********************************************************************************
//
// ETH Zürich / Robotic Fabrication Lab
// HIB C 13 / Stefano-Franscini-Platz 1
// CH-8093 Zürich
// 
// ***********************************************************************************
// 
// PROJECT     :  A061 Digital Casting System
// 
// FUNCTION    :  selector for mode control
// 
// AUTHOR      :  Weiting Chen
// 
// EMAIL       :  
// 
// Copyright   : 
//
// ***********************************************************************************


GVL_VAR.b_Mode_Manual := GVL_IO.ib_CC1_Button_Mode_Manual;
GVL_VAR.b_Mode_Laptop := GVL_IO.ib_CC1_Button_Mode_Laptop;

]]></ST>
    </Implementation>
    <LineIds Name="P_ModeSelector">
      <LineId Id="6" Count="17" />
      <LineId Id="5" Count="0" />
      <LineId Id="38" Count="0" />
      <LineId Id="25" Count="1" />
      <LineId Id="31" Count="0" />
      <LineId Id="27" Count="0" />
      <LineId Id="24" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>