<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="F_DecimalData" Id="{66d33ad8-e83a-4919-8f59-cd46dd00ddc3}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_DecimalData : LREAL
VAR_INPUT
	
	f_value_input : REAL;
	// decimal places
	n_decimal_digit : INT;
	// Round or not
	b_round_data: BOOL;

END_VAR
VAR_OUTPUT	
	f_value_output : REAL;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[f_value_output := STRING_TO_REAL(LREAL_TO_FMTSTR(TO_REAL(f_value_input), n_decimal_digit, b_round_data));
F_DecimalData := f_value_output

]]></ST>
    </Implementation>
    <LineIds Name="F_DecimalData">
      <LineId Id="115" Count="0" />
      <LineId Id="52" Count="0" />
      <LineId Id="32" Count="0" />
      <LineId Id="45" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>